
POST http://localhost:3000/api/auth/register 
Content-Type: application/json

{
    "name": "Paco",
    "email": "Pedrito@gmail.com" ,
    "password": "penelopecruz"
}


###


POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "probando111@gmail.com",
    "password": "penelopecruz"
}

###



PUT http://localhost:3000/api/auth/validation
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U3MDczMzU0YWRjN2U2OTIyNGM0MmMiLCJpYXQiOjE3NDMxOTM5MDgsImV4cCI6MTc0MzIwMTEwOH0.y2vYvMpxHyVRlITzWNK3TNQjAe0cqIzYpO1FJbKNcwk
Content-Type: application/json

{
 "verificationCode": 379039
}

### 
GET http://localhost:3000/api/auth/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U5MzQyYjQ0Njg1ZWU3OTkxNDM1ODQiLCJpYXQiOjE3NDMzMzY0OTEsImV4cCI6MTc0MzM0MzY5MX0.ucjiHO22wqUCo8n8WD99IBHyOLtYq5jatyMqi9DtYys


### Soft
DELETE http://localhost:3000/api/auth/user?soft=true
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U5MzQyYjQ0Njg1ZWU3OTkxNDM1ODQiLCJpYXQiOjE3NDMzMzY0OTEsImV4cCI6MTc0MzM0MzY5MX0.ucjiHO22wqUCo8n8WD99IBHyOLtYq5jatyMqi9DtYys
### Hard
DELETE http://localhost:3000/api/auth/user?soft=false
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U5MzQyYjQ0Njg1ZWU3OTkxNDM1ODQiLCJpYXQiOjE3NDMzMzY0OTEsImV4cCI6MTc0MzM0MzY5MX0.ucjiHO22wqUCo8n8WD99IBHyOLtYq5jatyMqi9DtYys